FROM golang:1.15-alpine as builder

WORKDIR /todo
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

RUN go build -o main .
WORKDIR /dist

FROM alpine:3.13
EXPOSE 8080
COPY --from=builder /dist .
ENTRYPOINT [ "/main" ]
