// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/Tak-Iwamoto/todo/application"
	"github.com/Tak-Iwamoto/todo/handler"
	"github.com/Tak-Iwamoto/todo/infrastructure"
)

// Injectors from wire.go:

func InitListTodoHandler() (*handler.ListTodoHandler, error) {
	todoRepository, err := infrastructure.NewTodoRepository()
	if err != nil {
		return nil, err
	}
	todoApp := application.NewTodoApp(todoRepository)
	listTodoHandler := handler.NewListTodoHandler(todoApp)
	return listTodoHandler, nil
}

func InitCreateTodoHandler() (*handler.CreateTodoHandler, error) {
	todoRepository, err := infrastructure.NewTodoRepository()
	if err != nil {
		return nil, err
	}
	todoApp := application.NewTodoApp(todoRepository)
	createTodoHandler := handler.NewCreateTodoHandler(todoApp)
	return createTodoHandler, nil
}
